"""
Django settings for django-nacl-fields project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    },
}

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3$+$r-(cl%@4b%id4-^b(=dnf=d71q-+rxus(b2qqm-rt28(w#'

INSTALLED_APPS = [
    'fields',
    'tests',
]

MIDDLEWARE_CLASSES = []

NACL_FIELDS_KEY = 'nrlrk1VlTEcjfKyubeTdYzZQwi2wuZN8YlyLbzO0Jgg='
